### ISSUE TITLE
Text Area Margin Bug

### ISSUE THREAD

**Issue by ihougland** [kthornbloom/JACKRABBIT-CMS#42]
![screen shot 2015-06-16 at 3 15 39 pm](https://cloud.githubusercontent.com/assets/11409848/8192218/a59a2664-143a-11e5-8ac6-bd4a77fffc29.png)

Sometimes, when adding content to a text area, the scroll bar for the text area will reach the end, but the text will show as seen in the screenshot.

**Comment by kthornbloom** [comment]
Is there a particular page this happened on? I can't seem to reproduce it.

**Comment by kthornbloom** [comment]
Fixed
