### ISSUE TITLE
Mailto links

### ISSUE THREAD

**Issue by ihougland** [kthornbloom/JACKRABBIT-CMS#44]
Not even sure if this is possible, but it would be nice to have a feature for clients to easily add email links. You can obviously do it by adding a hyperlink and changing the prefilled "http://" to "mailto:" but many clients will not know that. Not sure exactly what the best solution would be...maybe a separate "add email link" button, or text that would alert a client that they can add an email link by typing mailto: *email address* in the hyperlink box.

**Comment by kthornbloom** [comment]
Added tooltip explaining how to do this.
