### ISSUE TITLE
Add-on Textareas

### ISSUE THREAD

**Issue by jenthornbloom** [kthornbloom/JACKRABBIT-CMS#45]
Add text formatting options to add-on textareas (headers, bold, italic, etc.)

**Comment by kthornbloom** [comment]
Here's some sample code for how this will work. 

Do we need any more buttons?
The JS still needs updated so everything works properly. I'm adding a new 'miniedit.js' file.
   
    <div<ul class="mini-editor-toolbar">
								<li><a href="#" title="Bold" rel="B" onclick="document.execCommand ('bold', false, null);"><i class="fa fa-bold"></i></a>
								</li>
								<li><a href="#" title="Italic" rel="I" onclick="document.execCommand ('italic', false, null);"><i class="fa fa-italic"></i></a>
								</li>
								<li><a href="#" title="Underline" rel="U" onclick="document.execCommand('underline', false, null);"><i class="fa fa-underline"></i></a>
								</li>
								
								<li><a href="#" title="Subscript" rel="Sub" onclick="document.execCommand('subscript', false, null);"><i class="fa fa-subscript"></i></a>
								</li>
								<li><a href="#" title="Superscript" rel="Sup" onclick="document.execCommand('superscript', false, null);"><i class="fa fa-superscript"></i></a>
								</li>

								<li><a href="#" title="Bulleted List" rel="OL" onclick="document.execCommand('insertOrderedList', false, null); rangeMouseup();"><i class="fa fa-list-ol"></i></a>
								</li>
								<li><a href="#" title="Numbered List" rel="UL" onclick="document.execCommand('insertUnorderedList', false, null); rangeMouseup();"><i class="fa fa-list-ul"></i></a>
								</li>
								<li><a href="#" title="Add Link" onclick="createLink();"><i class="fa fa-link"></i></a>
								</li>
								<li><a href="#" title="Remove Link" onclick="document.execCommand('unlink', false, null);"><i class="fa fa-unlink"></i></a>
								</li>

								<li><a href="#" title="Horizontal Line" rel="hr" onclick="document.execCommand('insertHorizontalRule', false, null);"><i class="fa fa-minus"></i></a>
								</li>

							</ul> class="mini-editor" contenteditable="true">
					Lorem ipsum dolor sit amet, consectetu<br><br><ol><li><span style="color: rgb(82, 82, 82); font-size: 12px; background-color: rgb(255, 255, 255);">r adipisicing e</span><br></li></ol><br>lit, sed do eiusmod
					tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
					quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
	</div>

**Comment by kthornbloom** [comment]
This has been added.
