### ISSUE TITLE
Sidebar expand/collapse style suggestions

### ISSUE THREAD

**Issue by ihougland** [kthornbloom/JACKRABBIT-CMS#57]
*There may not be a viable solution to this*

I got super confused when I first used the new collapsable sidebar. The expand/collapse arrow on pages with sub-pages bumps each page title out of alignment (like they used to be). If you look at the lines that connect each level, you can see which pages are on which level. However, if you look at the page title, it starts to look very messy (see Administrators. All Administrator pages are parent pages except for one, Center Township Assessor, and this page looks at first glance to be on a different level.

**Comment by kthornbloom** [comment]
Just need Jen to remove <i class="fa fa-files-o"></i> on pages with submenus.

**Comment by kthornbloom** [comment]
Done!
